site_name: Ideasbox
pages:
- [index.md, Home]
- [install.md, Installation]
- [config.md, Configuration]
- [i18n.md, Translations]
theme: yeti
repo_url: https://github.com/ideas-box/ideasbox
site_description: Ideas Box server core application.
